
# exclude folders when recompile
spring:
  devtools:
    restart:
      exclude: statis/**, public/**
# additional exclude folders when recompile
      additional-exclude: java/**, test/**
# enable livereload function
    livereload:
      enabled: true
# change port
# server.port=
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

#빈검증기에서 사용하는 MessageSource의 한글 깨짐 방지  
  messages:
    basename: messages,ValidationMessages,PropertyNames
    cache-duration: 1
    encoding: UTF-8
    
#themeleaf 설정
  thymeleaf:
    view-names: thymeleaf/*
#    prefix: classpath:/templates/
    suffix: .html
    # thymeleaf사용중 수정사항이 생길때 수정을 하면 재시작을 해줘야 한다.
    # 이를 무시하고 브라우저 새로고침 시 수정사항 반영을 위해 false,
    #  운영반영시에는 true로 해야 한다.
    cache: false
    check-template-location: true
    
# MariaDB 설정
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://www.ntoworks.com:3306/db_library
    username: root
    password: n2works19!
mybatis: 
  type-aliases-package: com.example.demo.vo
  mapper-locations: mybatis/**/*.xml
  